version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    restart: always
    container_name: "mysql"
    volumes:
      - "./db:/var/lib/mysql"
      - "./src/main/resources/static:/var/lib/mysql-files"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timezone_follower
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  web:
    build: .
    links:
      - mysql
    container_name: Timezone-Follower-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=timezone_follower
      - DB_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_USER_PASSWORD=pass
    depends_on:
      - mysql